### ISSUE TITLE
Please add a license file 

### ISSUE THREAD

**Issue by unixorn** [mfulz/zsh-penmux#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Also, please include a readme with a list of what commands this plugin provides.

Thanks!

**Comment by mfulz** [comment]
License is added.
The Readme is ongoing and will be added soon

**Comment by mfulz** [comment]
Started basic [readme](https://github.com/mfulz/zsh-penmux/blob/master/README.md)

**Comment by unixorn** [comment]
Thanks! I'll add it once you close this issue. If you put a one-line summary in the readme, I'll use that as the base for the entry text.
